### PR TITLE
people

### PR DESCRIPTION
**Pull request by naomirajagukguk**
added my profile

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
congrats @naomirajagukguk for making it this far 👏  
The only thing to change is that the .md file should be named "_index.md". Could you try to make that change 😬 ?

**Comment by naomirajagukguk** [comment]
Hi Dom, I uploaded the same document here, I changed the file name on RStudio and my laptop, but I couldn't figure out how to change it on github. Do you think this is okay?

**Comment by DominiqueMakowski** [comment]
I see the new file with the correct, but it seems to be empty (it should be filled ) with [these info](https://raw.githubusercontent.com/RealityBending/RealityBending.github.io/main/content/authors/ana-neves/_index.md). If you're around campus today let me know on discord you can pop by my office and I'll show you directly on your laptop ☺️

**Comment by DominiqueMakowski** [comment]
Hi @naomirajagukguk how's it going with this ☺️

**Comment by naomirajagukguk** [comment]
Hi, sorry I forgot to update it on github.. just did it

**Pull request merged**
